### ISSUE TITLE
How to create shader module with SPIR-V format

### ISSUE THREAD

**Issue by mackst** [bglgwyng/pyVulkan#3]
I'm try to work out a Windows demo with pyVulkan. But I'm stuck at creating shader module with SPIR-V format. It crashed when it run in to vkCreateShaderModule function.
What I did:
```python
with open('vert.spv', 'rb') as sf:
    data = sf.read()
    dataArray = array.array('I', data)
    moduleCreateInfo = VkShaderModuleCreateInfo(flags=0,
                                                codeSize=dataArray.buffer_info()[1] * dataArray.itemsize,
                                                pCode=dataArray.tolist())
    shaderModule = vkCreateShaderModule(device, moduleCreateInfo, None)
```

**Comment by latte10am** [comment]
Sorry for my late reply. If it crashed, then it may not be the problem releted to the function you call. And I found my mistake on arguments's type of platform-specific apis and I fixed, I hope that this can solve your problem.
If it is not, I suggest you to try initializing VkShaderModuleCreateInfo with raw c data. It's possible that casting dataArray.tolist() to raw c data is not working proper now. It can be temporary solution.
After I set up my vulkan compatible windows pc soon, I'll fix this problem.

**Comment by mackst** [comment]
I tried that. It still crashed. I made a test version from scratch with cffi. It do not have this issue. I use the following code to create shader module
```python
with open(shaderFile, 'rb') as sf:
    code = sf.read()
    codeSize = len(code)
    c_code = ffi.new('unsigned char []', code)
    pcode = ffi.cast('uint32_t*', c_code)

    createInfo = ffi.new('VkShaderModuleCreateInfo*', {
        'sType' : VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO,
        'codeSize' : codeSize,
        'pCode' : pcode
    })

    shaderModule = ffi.new('VkShaderModule*')
    result = vkCreateShaderModule(device, createInfo, ffi.NULL, shaderModule)
    if result != VK_SUCCESS:
        raise Exception('failed to create shader module!')
```
I use your _vulkan.h as header file and it crashed again.

**Comment by bglgwyng** [comment]
Could you post the full source code?

**Comment by bglgwyng** [comment]
I fixed some bugs in strucrue initialization on windows. Maybe it solves your problem too.

**Comment by mackst** [comment]
yeah, fixed.
